### ISSUE TITLE
Error in parameter assignation

### ISSUE THREAD

**Issue by SFBertolin** [edward-burn/OHDSI-COVID19-HopitalisationsCharacterisation-Pediatrics#1]
Hi @edward-burn , in the CodeToRun.R code there's an assignation to FALSe instead of FALSE.

https://github.com/edward-burn/OHDSI-COVID19-HopitalisationsCharacterisation-Pediatrics/blob/fccb7007e59354a33348af624b417de4f2038fc7/Influenza%20Cohort%20Diagnostics/extras/CodeToRun.R#L59

R does not recognize the assignation and the program crashes. Changing the last e to uppercase could save some time to the people running the package

**Comment by edward-burn** [comment]
fixed, thanks!
